name: update site

on:
    push:
        branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name techbrett2 --auth-mode login -d '$web' -s . --overwrite
    - name: Purge CDN endpoint
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "techbrett2" --name "techbrett2" --resource-group "techbrett"
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
