name: Update Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: Azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload Files to Blob Storage
      run: |
        az storage blob upload-batch --account-name techbrett2 --auth-mode login -d '$web' -s . --overwrite

    - name: Purge CDN Endpoint
      run: |
        az cdn endpoint purge --content-paths "/*" --profile-name "techbrett2" --name "techbrett2" --resource-group "techbrett"

    - name: Azure Logout
      run: |
        az logout
      if: always()
