name: Update Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: Azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
         az storage blob upload-batch --account-name techbrett2 --auth-mode key --account-key '${{ secrets.AZURE_STORAGE_KEY }}' -d '$web' -s . --overwrite

    - name: Purge CDN Endpoint
      run: |
        az cdn endpoint purge --content-paths "/*" --profile-name "techbrett2" --name "techbrett2" --resource-group "techbrett"

    - name: Azure Logout
      run: |
        az logout
      if: always()
